# Best Bikes in India (bikewala Website): Web Scraping and Data Analysis Project

## Objective

1. **Feature-Wise Bike Analysis**
   - Analyze bikes available in India based on their price, engine capacity (CC), mileage, maximum power, torque, fuel efficiency, and other specifications.
   - Compare bikes based on performance, comfort, safety features, fuel economy, and maintenance-related factors.
   - Identify bikes that offer the best combination of features, performance, and value for money.

2. **Brand-Wise and Model-Wise Bike Analysis**
   - Compare popular bike brands and models in India based on their prices, specifications, mileage, and features.
   - Analyze differences between commuter bikes, sports bikes, cruisers, adventure bikes, and touring bikes.
   - Identify the best-performing brands and models within different price ranges and riding categories.

3. **Price-Wise Bike Analysis**
   - Categorize bikes into different price segments and compare their features and specifications.
   - Identify the best bikes under ₹1 lakh, ₹1.5 lakh, ₹2 lakh, and ₹3 lakh.
   - Analyze the relationship between bike price, engine capacity, mileage, power, and available features.

4. **Best Bike Recommendation**
   - Rank bikes based on multiple criteria, including price, mileage, performance, safety, comfort, and features.
   - Develop a scoring system to identify the best bikes for different requirements, such as daily commuting, long-distance touring, sports riding, and fuel efficiency.
   - Recommend the best overall bikes and the best value-for-money options in each category using data-driven analysis.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd, numpy as np
import re
import time

In [2]:
models_nonev = []
ratings_noev = []
members_noev = []
ccs_noev = []
kmpls_noev = []
bhps_noev = []
kgs_noev = []
prices_noev = []

In [3]:
models_ev = []
ratings_ev = []
members_ev = []
kmphs_ev = []
kms_ev = []
kgs_ev = []
kwhs_ev = []
prices_ev = []

#### Best Scooters Extraction

In [4]:
for page_no in range(1,16):

    url = f"https://www.bikewale.com/best-scooters-in-india/?sortOrder1=desc&sortField1=modelPopularity&pageNumber={page_no}"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8",
        "Referer": "https://www.google.com/"
    }
    time.sleep(3)
    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text,"html.parser")
    cards_list = soup.find_all("div",class_="o-f o-hl o-aE")

    for card in cards_list:

        ev = card.select_one("div.o-C.o-d.o-k.o-f5.o-ew.uZURE8.o-gS.o-ib+span")

        if ev:
            
            brand_model = card.select_one("span.o-jJ.o-j3.o-js.o-ez") #1
            
            if brand_model:
                models_ev.append(brand_model.text)
            else:
                models_ev.append(np.nan)
                

            rating_no = card.select_one("div.o-eg.o-f.o-aE")  #2
            
            if rating_no:
                text = rating_no.text
                rating_no_reg = re.findall(r"(\d+\.\d+)/5",text)
                rating_mem_reg = re.findall(r"/5(\d+)",text)

                if rating_no_reg:
                    ratings_ev.append(float(rating_no_reg[0]))
                else:
                    ratings_ev.append(np.nan)
                
                if rating_mem_reg:
                    members_ev.append(int(rating_mem_reg[0]))
                else:
                    members_ev.append(np.nan)
            else:
                ratings_ev.append(np.nan)
                members_ev.append(np.nan)


            price = card.select_one("span.o-jJ.o-jr.o-j3.o-kJ")   #3

            if price:
                
                text = price.text
                price_reg = text.split()[1].replace(",","")
                prices_ev.append(price_reg)
                
            else:
                prices_ev.append(np.nan)

                

            list_specs = card.select_one("div.o-o.FTJfQA.o-iT.o-ei")  #4

            kmph = np.nan
            km = np.nan
            kg = np.nan
            kwh = np.nan
            
            if list_specs:
                specs = list_specs.get_text(strip=True).split("|")
            
                for spec in specs:
                    spec = spec.strip().lower()
            
                    if "kmph" in spec:
                        kmph = spec
            
                    elif "kwh" in spec:
                        kwh = spec
            
                    elif "km" in spec:
                        km = spec
            
                    elif "kg" in spec:
                        kg = spec
            
            kmphs_ev.append(kmph)
            kms_ev.append(km)
            kgs_ev.append(kg)
            kwhs_ev.append(kwh)

        
                        
        else:
            
            brand_model = card.select_one("span.o-jJ.o-j3.o-js.o-ez") #1
            
            if brand_model:
                models_nonev.append(brand_model.text)
            else:
                models_nonev.append(np.nan)


            rating_no = card.select_one("div.o-eg.o-f.o-aE")  #2
            
            if rating_no:
                text = rating_no.text
                rating_no_reg = re.findall(r"(\d+\.\d+)/5",text)
                rating_mem_reg = re.findall(r"/5(\d+)",text)

                if rating_no_reg:
                    ratings_noev.append(float(rating_no_reg[0]))
                else:
                    ratings_noev.append(np.nan)

                if rating_mem_reg:
                    members_noev.append(int(rating_mem_reg[0]))
                else:
                    members_noev.append(np.nan)
            else:
                ratings_noev.append(np.nan)
                members_noev.append(np.nan)
                

            price = card.select_one("span.o-jJ.o-jr.o-j3.o-kJ")   #3

            if price:
                
                text = price.text
                price_reg = text.split()[1].replace(",","")
                prices_noev.append(price_reg)
                
            else:
                prices_noev.append(np.nan)


            list_specs = card.select_one("div.o-o.FTJfQA.o-iT.o-ei")  #4
            
            cc = np.nan
            kmpl = np.nan
            bhp = np.nan
            kg = np.nan
            
            if list_specs:
                specs = list_specs.get_text(strip=True).split("|")
            
                for spec in specs:
                    spec = spec.strip().lower()
            
                    if "cc" in spec:
                        cc = spec
                    elif "kmpl" in spec:
                        kmpl = spec
                    elif "bhp" in spec:
                        bhp = spec
                    elif "kg" in spec:
                        kg = spec
            
            ccs_noev.append(cc)  
            kmpls_noev.append(kmpl)
            bhps_noev.append(bhp)
            kgs_noev.append(kg)

#### Sports-Bike Extraction

In [5]:
page_no = 1

while True:
    

    url = f"https://www.bikewale.com/best-sports-bikes-in-india/?pageNumber={page_no}&pageSize=30&bodyStyleIds=12"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8",
        "Referer": "https://www.google.com/"
    }
    time.sleep(3)
    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text,"html.parser")
    cards_list = soup.find_all("div",class_="o-f o-hl o-aE")

    if not cards_list:
        print("No more bikes found. Stopping.")
        break

    for card in cards_list:

        ev = card.select_one("div.o-C.o-d.o-k.o-f5.o-ew.uZURE8.o-gS.o-ib+span")

        if ev:
            
            brand_model = card.select_one("span.o-jJ.o-j3.o-js.o-ez") #1
            
            if brand_model:
                models_ev.append(brand_model.text)
            else:
                models_ev.append(np.nan)
                

            rating_no = card.select_one("div.o-eg.o-f.o-aE")  #2
            
            if rating_no:
                text = rating_no.text
                rating_no_reg = re.findall(r"(\d+\.\d+)/5",text)
                rating_mem_reg = re.findall(r"/5(\d+)",text)

                if rating_no_reg:
                    ratings_ev.append(float(rating_no_reg[0]))
                else:
                    ratings_ev.append(np.nan)
                
                if rating_mem_reg:
                    members_ev.append(int(rating_mem_reg[0]))
                else:
                    members_ev.append(np.nan)
            else:
                ratings_ev.append(np.nan)
                members_ev.append(np.nan)


            price = card.select_one("span.o-jJ.o-jr.o-j3.o-kJ")   #3

            if price:
                
                text = price.text
                price_reg = text.split()[1].replace(",","")
                prices_ev.append(price_reg)
                
            else:
                prices_ev.append(np.nan)

                

            list_specs = card.select_one("div.o-o.FTJfQA.o-iT.o-ei")  #4

            kmph = np.nan
            km = np.nan
            kg = np.nan
            kwh = np.nan
            
            if list_specs:
                specs = list_specs.get_text(strip=True).split("|")
            
                for spec in specs:
                    spec = spec.strip().lower()
            
                    if "kmph" in spec:
                        kmph = spec
            
                    elif "kwh" in spec:
                        kwh = spec
            
                    elif "km" in spec:
                        km = spec
            
                    elif "kg" in spec:
                        kg = spec
            
            kmphs_ev.append(kmph)
            kms_ev.append(km)
            kgs_ev.append(kg)
            kwhs_ev.append(kwh)

        
                        
        else:
            
            brand_model = card.select_one("span.o-jJ.o-j3.o-js.o-ez") #1
            
            if brand_model:
                models_nonev.append(brand_model.text)
            else:
                models_nonev.append(np.nan)


            rating_no = card.select_one("div.o-eg.o-f.o-aE")  #2
            
            if rating_no:
                text = rating_no.text
                rating_no_reg = re.findall(r"(\d+\.\d+)/5",text)
                rating_mem_reg = re.findall(r"/5(\d+)",text)

                if rating_no_reg:
                    ratings_noev.append(float(rating_no_reg[0]))
                else:
                    ratings_noev.append(np.nan)

                if rating_mem_reg:
                    members_noev.append(int(rating_mem_reg[0]))
                else:
                    members_noev.append(np.nan)
            else:
                ratings_noev.append(np.nan)
                members_noev.append(np.nan)
                

            price = card.select_one("span.o-jJ.o-jr.o-j3.o-kJ")   #3

            if price:
                
                text = price.text
                price_reg = text.split()[1].replace(",","")
                prices_noev.append(price_reg)
                
            else:
                prices_noev.append(np.nan)


            list_specs = card.select_one("div.o-o.FTJfQA.o-iT.o-ei")  #4
            
            cc = np.nan
            kmpl = np.nan
            bhp = np.nan
            kg = np.nan
            
            if list_specs:
                specs = list_specs.get_text(strip=True).split("|")
            
                for spec in specs:
                    spec = spec.strip().lower()
            
                    if "cc" in spec:
                        cc = spec
                    elif "kmpl" in spec:
                        kmpl = spec
                    elif "bhp" in spec:
                        bhp = spec
                    elif "kg" in spec:
                        kg = spec
            
            ccs_noev.append(cc)  
            kmpls_noev.append(kmpl)
            bhps_noev.append(bhp)
            kgs_noev.append(kg)
        
    page_no+=1

No more bikes found. Stopping.

#### Cruiser Bikes Extraction

In [6]:
page_no = 1

while True:
    

    url = f"https://www.bikewale.com/best-cruiser-bikes-in-india/?pageNumber={page_no}&pageSize=30&bodyStyleIds=1"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8",
        "Referer": "https://www.google.com/"
    }
    time.sleep(3)
    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text,"html.parser")
    cards_list = soup.find_all("div",class_="o-f o-hl o-aE")

    if not cards_list:
        print("No more bikes found. Stopping.")
        break

    for card in cards_list:

        ev = card.select_one("div.o-C.o-d.o-k.o-f5.o-ew.uZURE8.o-gS.o-ib+span")

        if ev:
            
            brand_model = card.select_one("span.o-jJ.o-j3.o-js.o-ez") #1
            
            if brand_model:
                models_ev.append(brand_model.text)
            else:
                models_ev.append(np.nan)
                

            rating_no = card.select_one("div.o-eg.o-f.o-aE")  #2
            
            if rating_no:
                text = rating_no.text
                rating_no_reg = re.findall(r"(\d+\.\d+)/5",text)
                rating_mem_reg = re.findall(r"/5(\d+)",text)

                if rating_no_reg:
                    ratings_ev.append(float(rating_no_reg[0]))
                else:
                    ratings_ev.append(np.nan)
                
                if rating_mem_reg:
                    members_ev.append(int(rating_mem_reg[0]))
                else:
                    members_ev.append(np.nan)
            else:
                ratings_ev.append(np.nan)
                members_ev.append(np.nan)


            price = card.select_one("span.o-jJ.o-jr.o-j3.o-kJ")   #3

            if price:
                
                text = price.text
                price_reg = text.split()[1].replace(",","")
                prices_ev.append(price_reg)
                
            else:
                prices_ev.append(np.nan)

                

            list_specs = card.select_one("div.o-o.FTJfQA.o-iT.o-ei")  #4

            kmph = np.nan
            km = np.nan
            kg = np.nan
            kwh = np.nan
            
            if list_specs:
                specs = list_specs.get_text(strip=True).split("|")
            
                for spec in specs:
                    spec = spec.strip().lower()
            
                    if "kmph" in spec:
                        kmph = spec
            
                    elif "kwh" in spec:
                        kwh = spec
            
                    elif "km" in spec:
                        km = spec
            
                    elif "kg" in spec:
                        kg = spec
            
            kmphs_ev.append(kmph)
            kms_ev.append(km)
            kgs_ev.append(kg)
            kwhs_ev.append(kwh)

        
                        
        else:
            
            brand_model = card.select_one("span.o-jJ.o-j3.o-js.o-ez") #1
            
            if brand_model:
                models_nonev.append(brand_model.text)
            else:
                models_nonev.append(np.nan)


            rating_no = card.select_one("div.o-eg.o-f.o-aE")  #2
            
            if rating_no:
                text = rating_no.text
                rating_no_reg = re.findall(r"(\d+\.\d+)/5",text)
                rating_mem_reg = re.findall(r"/5(\d+)",text)

                if rating_no_reg:
                    ratings_noev.append(float(rating_no_reg[0]))
                else:
                    ratings_noev.append(np.nan)

                if rating_mem_reg:
                    members_noev.append(int(rating_mem_reg[0]))
                else:
                    members_noev.append(np.nan)
            else:
                ratings_noev.append(np.nan)
                members_noev.append(np.nan)
                

            price = card.select_one("span.o-jJ.o-jr.o-j3.o-kJ")   #3

            if price:
                
                text = price.text
                price_reg = text.split()[1].replace(",","")
                prices_noev.append(price_reg)
                
            else:
                prices_noev.append(np.nan)


            list_specs = card.select_one("div.o-o.FTJfQA.o-iT.o-ei")  #4
            
            cc = np.nan
            kmpl = np.nan
            bhp = np.nan
            kg = np.nan
            
            if list_specs:
                specs = list_specs.get_text(strip=True).split("|")
            
                for spec in specs:
                    spec = spec.strip().lower()
            
                    if "cc" in spec:
                        cc = spec
                    elif "kmpl" in spec:
                        kmpl = spec
                    elif "bhp" in spec:
                        bhp = spec
                    elif "kg" in spec:
                        kg = spec
            
            ccs_noev.append(cc)  
            kmpls_noev.append(kmpl)
            bhps_noev.append(bhp)
            kgs_noev.append(kg)
        
    page_no+=1

No more bikes found. Stopping.

In [7]:
print("EV lengths:")
print(
    len(models_ev),
    len(ratings_ev),
    len(members_ev),
    len(prices_ev),
    len(kmphs_ev),
    len(kms_ev),
    len(kgs_ev),
    len(kwhs_ev)
)

print("Non-EV lengths:")
print(
    len(models_nonev),
    len(ratings_noev),
    len(members_noev),
    len(prices_noev),
    len(ccs_noev),
    len(kmpls_noev),
    len(bhps_noev),
    len(kgs_noev)
)

EV lengths:
114 114 114 114 114 114 114 114
Non-EV lengths:
441 441 441 441 441 441 441 441

In [8]:
df_ev = pd.DataFrame({
    "Model": models_ev,
    "Rating": ratings_ev,
    "Rating_Members": members_ev,
    "Price": prices_ev,
    "Top_Speed": kmphs_ev,
    "Range": kms_ev,
    "Weight": kgs_ev,
    "Battery": kwhs_ev
})

df_ev.head()

,Model,Rating,Rating_Members,Price,Top_Speed,Range,Weight,Battery
0,TVS iQube,3.7,916.0,119450,82 kmph,212 km,129.7 kg,5.3 kwh
1,Bajaj Chetak,3.7,774.0,120236,80 kmph,153 km,NaN,3.5 kwh
2,Ather Konarc,4.8,54.0,101209,70 kmph,161 km,129 kg,3.5 kwh
3,TVS Orbiter,4.4,201.0,102434,68 kmph,158 km,112 kg,3.1 kwh
4,Ather Rizta,4.4,406.0,121178,80 kmph,160 km,119 kg,3.5 kwh

In [9]:
df_nonev = pd.DataFrame({
    "Model": models_nonev,
    "Rating": ratings_noev,
    "Rating_Members": members_noev,
    "Price": prices_noev,
    "Engine_CC": ccs_noev,
    "Mileage": kmpls_noev,
    "Power": bhps_noev,
    "Weight": kgs_noev
})

df_nonev.head()

,Model,Rating,Rating_Members,Price,Engine_CC,Mileage,Power,Weight
0,TVS Raider 125,4.4,2971.0,86943,124.8 cc,56.7 kmpl,11.2 bhp,123 kg
1,Royal Enfield Hunter 350,4.7,1843.0,137640,349.34 cc,36.2 kmpl,20.2 bhp,181 kg
2,Royal Enfield Classic 350,4.7,82.0,188934,349 cc,41.55 kmpl,20.2 bhp,195 kg
3,Royal Enfield Bullet 350,4.7,1593.0,166981,349 cc,35 kmpl,20.2 bhp,195 kg
4,TVS Ronin,4.6,1181.0,130809,225.9 cc,42 kmpl,20.1 bhp,160 kg

In [10]:
df_ev.to_csv("Electric_Vehicles.csv", index=False)

df_nonev.to_csv("Non_Electric_Vehicles.csv", index=False)