# Best Bikes in India (bikewala Website): Web Scraping and Data Analysis Project

## Objective

1. **Feature-Wise Bike Analysis**
   - Analyze bikes available in India based on their price, engine capacity (CC), mileage, maximum power, torque, fuel efficiency, and other specifications.
   - Compare bikes based on performance, comfort, safety features, fuel economy, and maintenance-related factors.
   - Identify bikes that offer the best combination of features, performance, and value for money.

2. **Brand-Wise and Model-Wise Bike Analysis**
   - Compare popular bike brands and models in India based on their prices, specifications, mileage, and features.
   - Analyze differences between commuter bikes, sports bikes, cruisers, adventure bikes, and touring bikes.
   - Identify the best-performing brands and models within different price ranges and riding categories.

3. **Price-Wise Bike Analysis**
   - Categorize bikes into different price segments and compare their features and specifications.
   - Identify the best bikes under ₹1 lakh, ₹1.5 lakh, ₹2 lakh, and ₹3 lakh.
   - Analyze the relationship between bike price, engine capacity, mileage, power, and available features.

4. **Best Bike Recommendation**
   - Rank bikes based on multiple criteria, including price, mileage, performance, safety, comfort, and features.
   - Develop a scoring system to identify the best bikes for different requirements, such as daily commuting, long-distance touring, sports riding, and fuel efficiency.
   - Recommend the best overall bikes and the best value-for-money options in each category using data-driven analysis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_nonev  = pd.read_csv("Non_Electric_Vehicles.csv")
df_ev = pd.read_csv("Electric_Vehicles.csv")

#  Non_Electric_Vehicles

In [3]:
df_nonev.head(5)

,Model,Rating,Rating_Members,Price,Engine_CC,Mileage,Power,Weight
0,TVS Raider 125,4.4,2971.0,86943,124.8 cc,56.7 kmpl,11.2 bhp,123 kg
1,Royal Enfield Hunter 350,4.7,1843.0,137640,349.34 cc,36.2 kmpl,20.2 bhp,181 kg
2,Royal Enfield Classic 350,4.7,82.0,188934,349 cc,41.55 kmpl,20.2 bhp,195 kg
3,Royal Enfield Bullet 350,4.7,1593.0,166981,349 cc,35 kmpl,20.2 bhp,195 kg
4,TVS Ronin,4.6,1181.0,130809,225.9 cc,42 kmpl,20.1 bhp,160 kg

In [4]:
df_nonev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Model           441 non-null    object
 1   Rating          334 non-null    float64
 2   Rating_Members  400 non-null    float64
 3   Price           441 non-null    int64
 4   Engine_CC       441 non-null    object
 5   Mileage         353 non-null    object
 6   Power           428 non-null    object
 7   Weight          427 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 27.7+ KB

In [5]:
df_nonev.describe()

           Rating  Rating_Members         Price
count  334.000000      400.000000  4.410000e+02
mean     4.410778      278.735000  9.037660e+05
std      0.522874      687.137249  1.166714e+06
min      1.700000        1.000000  4.792200e+04
25%      4.400000        5.000000  1.665860e+05
50%      4.500000       20.000000  3.392690e+05
75%      4.700000      186.500000  1.390600e+06
max      4.900000     4883.000000  1.000000e+07

In [6]:
df = df_nonev.copy()

In [7]:
df.columns

Index(['Model', 'Rating', 'Rating_Members', 'Price', 'Engine_CC', 'Mileage',
       'Power', 'Weight'],
      dtype='object')

In [8]:
df.shape

(441, 8)

In [9]:
df["Engine_CC"] = pd.to_numeric(df["Engine_CC"].str.replace("cc","",case = False, regex=True),errors = "coerce")
df["Mileage"] = pd.to_numeric(df["Mileage"].str.replace("kmpl","",case = False, regex=True),errors = "coerce")
df["Power"] = pd.to_numeric(df["Power"].str.replace("bhp","",case = False, regex=True),errors = "coerce")
df["Weight"] = pd.to_numeric(df["Weight"].str.replace("kg","",case = False, regex=True),errors = "coerce")

In [10]:
df.dtypes

Model              object
Rating            float64
Rating_Members    float64
Price               int64
Engine_CC         float64
Mileage           float64
Power             float64
Weight            float64
dtype: object

In [11]:
multi_word_brands = ["Royal Enfield", "Moto Morini", "Moto Guzzi", "QJ Motor", "Brixton Motorcycles"]

def get_brand(name):
    name = name.strip()
    for b in multi_word_brands:
        if name.startswith(b):
            return b
    return name.split()[0]

df["Brand"] = df["Model"].apply(get_brand)

In [12]:
df = df.rename(columns = {"Price": "Price(Rs)", "Mileage": "Mileage(kmpl)","Engine_CC":"Engine(cc)","Power": "Power(bhp)" ,"Weight":"Weight(kg)"})

In [13]:
df = df[["Brand" ,"Model" ,"Rating"	,"Rating_Members" ,"Price(Rs)",	"Engine(cc)" , "Mileage(kmpl)" ,"Power(bhp)" ,"Weight(kg)"]]

In [14]:
df[df.duplicated(keep= False)].sort_values(by="Model")

,Brand,Model,Rating,Rating_Members,Price(Rs),Engine(cc),Mileage(kmpl),Power(bhp),Weight(kg)
342,Aprilia,Aprilia RS 457,4.7,34.0,433416,457.0,24.0,46.90,175.0
62,Aprilia,Aprilia RS 457,4.7,34.0,433416,457.0,24.0,46.90,175.0
225,Aprilia,Aprilia RS 660,4.2,5.0,1895878,659.0,NaN,98.56,183.0
366,Aprilia,Aprilia RS 660,4.2,5.0,1895878,659.0,NaN,98.56,183.0
126,Aprilia,Aprilia Tuono 457,4.7,20.0,406181,457.0,29.0,46.90,175.0
...,...,...,...,...,...,...,...,...,...
337,Yamaha,Yamaha R15 V4,4.8,1560.0,175692,155.0,46.0,18.10,141.0
120,Yamaha,Yamaha R15S,4.8,260.0,160026,155.0,46.0,18.10,142.0
343,Yamaha,Yamaha R15S,4.8,260.0,160026,155.0,46.0,18.10,142.0
339,Yamaha,Yamaha R2,4.5,28.0,231501,204.0,38.0,26.50,150.0
48,Yamaha,Yamaha R2,4.5,28.0,231501,204.0,38.0,26.50,150.0

In [15]:
df.drop_duplicates(inplace = True)

In [16]:
df[df[["Engine(cc)","Mileage(kmpl)"	,"Power(bhp)",	"Weight(kg)"]].isna().sum(axis=1) >= 3 ]

,Brand,Model,Rating,Rating_Members,Price(Rs),Engine(cc),Mileage(kmpl),Power(bhp),Weight(kg)
53,Honda,Honda XR300 Rally,4.2,5.0,208000,293.5,NaN,NaN,NaN
110,Honda,Honda XR300L,3.8,3.0,183000,293.5,NaN,NaN,NaN

In [17]:
df = df[~(df[["Engine(cc)","Mileage(kmpl)","Power(bhp)",	"Weight(kg)"]].isna().sum(axis=1) >= 3) ]

In [18]:
df.shape

(335, 9)

In [19]:
df.isna().sum()

Brand              0
Model              0
Rating            79
Rating_Members    30
Price(Rs)          0
Engine(cc)         0
Mileage(kmpl)     65
Power(bhp)         8
Weight(kg)         9
dtype: int64

In [20]:
df.isna().mean()*100

Brand              0.000000
Model              0.000000
Rating            23.582090
Rating_Members     8.955224
Price(Rs)          0.000000
Engine(cc)         0.000000
Mileage(kmpl)     19.402985
Power(bhp)         2.388060
Weight(kg)         2.686567
dtype: float64

In [21]:
df[df[["Rating_Members","Rating"]].isna().sum(axis=1)>=2].count()

Brand             30
Model             30
Rating             0
Rating_Members     0
Price(Rs)         30
Engine(cc)        30
Mileage(kmpl)     18
Power(bhp)        30
Weight(kg)        26
dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 335 entries, 0 to 336
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           335 non-null    object
 1   Model           335 non-null    object
 2   Rating          256 non-null    float64
 3   Rating_Members  305 non-null    float64
 4   Price(Rs)       335 non-null    int64
 5   Engine(cc)      335 non-null    float64
 6   Mileage(kmpl)   270 non-null    float64
 7   Power(bhp)      327 non-null    float64
 8   Weight(kg)      326 non-null    float64
dtypes: float64(6), int64(1), object(2)
memory usage: 26.2+ KB

In [23]:
# Step 1: Create engine groups
df["Engine_group"] = pd.cut(
    df["Engine(cc)"],
    bins=[0, 125, 160, 250, 400, 700, 1000, 1300, 3000],
    labels=[
        "upto125", "126-160", "161-250", "251-400",
        "401-700", "701-1000", "1001-1300", "1300plus"
    ]
)

In [24]:
def fill_missing(df, column, tries):
    for group in tries:
        middle = df.groupby(group, observed=True)[column].transform("median")
        df[column] = df[column].fillna(middle)


fill_missing(df, "Power(bhp)", [["Brand", "Engine_group"], ["Engine_group"]])
fill_missing(df, "Weight(kg)", [["Brand", "Engine_group"], ["Engine_group"]])
fill_missing(df, "Mileage(kmpl)", [["Brand", "Engine_group"], ["Engine_group"]])

In [25]:
df["Rating_Imputed"] = df["Rating"].isna()

df["Rating"] = df["Rating"].fillna(
    df.groupby("Brand")["Rating"].transform("median")
)

df["Rating"] = df["Rating"].fillna(df["Rating"].median())

df["Rating_Clean"] = df["Rating"].where(~df["Rating_Imputed"])

In [26]:
df["Rating_Members"] = df["Rating_Members"].fillna(0)

In [27]:
df[["Rating_Members","Rating","Rating_Imputed","Rating_Clean"]]

     Rating_Members  Rating  Rating_Imputed  Rating_Clean
0            2971.0    4.40           False           4.4
1            1843.0    4.70           False           4.7
2              82.0    4.70           False           4.7
3            1593.0    4.70           False           4.7
4            1181.0    4.60           False           4.6
..              ...     ...             ...           ...
332             0.0    4.75            True           NaN
333             1.0    4.75            True           NaN
334             2.0    4.75            True           NaN
335             0.0    4.40            True           NaN
336             0.0    4.40            True           NaN

[335 rows x 4 columns]

In [28]:
print((df.isnull().mean() * 100).round(2))

Brand              0.00
Model              0.00
Rating             0.00
Rating_Members     0.00
Price(Rs)          0.00
Engine(cc)         0.00
Mileage(kmpl)      0.00
Power(bhp)         0.00
Weight(kg)         0.00
Engine_group       0.00
Rating_Imputed     0.00
Rating_Clean      23.58
dtype: float64

In [29]:
df.drop(columns=["Engine_group"], inplace=True)

# Electric_Vehicles

In [30]:
df_ev.head(5)

,Model,Rating,Rating_Members,Price,Top_Speed,Range,Weight,Battery
0,TVS iQube,3.7,916.0,119450,82 kmph,212 km,129.7 kg,5.3 kwh
1,Bajaj Chetak,3.7,774.0,120236,80 kmph,153 km,NaN,3.5 kwh
2,Ather Konarc,4.8,54.0,101209,70 kmph,161 km,129 kg,3.5 kwh
3,TVS Orbiter,4.4,201.0,102434,68 kmph,158 km,112 kg,3.1 kwh
4,Ather Rizta,4.4,406.0,121178,80 kmph,160 km,119 kg,3.5 kwh

In [31]:
df_ev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Model           114 non-null    object
 1   Rating          97 non-null     float64
 2   Rating_Members  108 non-null    float64
 3   Price           114 non-null    int64
 4   Top_Speed       112 non-null    object
 5   Range           114 non-null    object
 6   Weight          96 non-null     object
 7   Battery         113 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 7.3+ KB

In [32]:
df_ev.describe()

          Rating  Rating_Members         Price
count  97.000000      108.000000  1.140000e+02
mean    3.896907       83.888889  1.451203e+05
std     0.658827      160.848180  1.469218e+05
min     2.300000        1.000000  5.499900e+04
25%     3.300000        8.000000  9.013650e+04
50%     4.100000       25.500000  1.151550e+05
75%     4.400000       59.250000  1.501835e+05
max     4.900000      916.000000  1.525000e+06

In [33]:
df_ev.columns

Index(['Model', 'Rating', 'Rating_Members', 'Price', 'Top_Speed', 'Range',
       'Weight', 'Battery'],
      dtype='object')

In [34]:
df_ev.shape

(114, 8)

In [35]:
df1 = df_ev.copy()

In [36]:
df1[df1["Range"].str.strip().str.contains("km/kg" , na = False)]

# it is cng so i found only one record so iam removing it

,Model,Rating,Rating_Members,Price,Top_Speed,Range,Weight,Battery
6,Bajaj Freedom,4.6,761.0,104240,NaN,91 km/kg,149 kg,NaN

In [37]:
df1.drop(index = 6 , inplace = True)

In [38]:
df1.head()

,Model,Rating,Rating_Members,Price,Top_Speed,Range,Weight,Battery
0,TVS iQube,3.7,916.0,119450,82 kmph,212 km,129.7 kg,5.3 kwh
1,Bajaj Chetak,3.7,774.0,120236,80 kmph,153 km,NaN,3.5 kwh
2,Ather Konarc,4.8,54.0,101209,70 kmph,161 km,129 kg,3.5 kwh
3,TVS Orbiter,4.4,201.0,102434,68 kmph,158 km,112 kg,3.1 kwh
4,Ather Rizta,4.4,406.0,121178,80 kmph,160 km,119 kg,3.5 kwh

In [39]:
df1["Top_Speed"] = pd.to_numeric(df1["Top_Speed"].str.replace("kmph","",case = False, regex=True),errors = "coerce")
df1["Range"] = pd.to_numeric(df1["Range"].str.replace("km","",case = False, regex=True),errors = "coerce")
df1["Weight"] = pd.to_numeric(df1["Weight"].str.replace("kg","",case = False, regex=True),errors = "coerce")
df1["Battery"] = pd.to_numeric(df1["Battery"].str.replace("kwh","",case = False, regex=True),errors = "coerce")

In [40]:
df1.dtypes

Model              object
Rating            float64
Rating_Members    float64
Price               int64
Top_Speed         float64
Range               int64
Weight            float64
Battery           float64
dtype: object

In [41]:
df1["Model"].unique()

array(['TVS iQube', 'Bajaj Chetak', 'Ather Konarc', 'TVS Orbiter',
       'Ather Rizta', 'VIDA VX2', 'Ather 450X', 'River Indie', 'OLA S1 X',
       'Bajaj Chetak C25', 'OLA Roadster', 'Ather 450S', 'OLA S1 Z',
       'Ampere Magnus G Max', 'Simple Wave', 'Simple One',
       'Honda Activa e', 'OLA Roadster Pro', 'Ather 450 Apex',
       'Ampere Magnus Neo', 'OLA S1 Pro', 'Yamaha EC 06', 'Ampere Nexus',
       'OLA Roadster X Plus', 'BGauss C12', 'Honda QC1',
       'Royal Enfield Flying Flea C6', 'OLA Roadster X', 'VLF Strada',
       'Ultraviolette X47 Crossover', 'VIDA V2', 'Oben Rorr EVO',
       'Honda QC3', 'Suzuki E Access', 'Ultraviolette F77 Mach 2',
       'Ampere Reo', 'Simple Ultra', 'Kinetic DX', 'Revolt RV400',
       'TVS X', 'Avore EX2', 'BMW CE 02', 'Lectrix SX25', 'Revolt RV1',
       'Ferrato FEV 650', 'Yamaha Aerox E', 'Kinetic Green E Luna',
       'Ultraviolette F77 SuperStreet', 'Avore EX2S', 'Revolt RVX',
       'Keeway Hypevolt-R', 'Oben Rorr EZ Sigma', 'Matter AERA',
       'Revolt RV BlazeX', 'Okinawa R30', 'Odysse Evoqis',
       'VLF Tennis 1500', 'BMW CE 04', 'Avore EX1', 'Evolet Pony',
       'BGauss Oowah', 'Joy e-bike Gen Nxt', 'Raptee HV T30',
       'BGauss C12 MaxR', 'Lectrix Nduro', 'Okinawa Lite',
       'BGauss BG RUV 350', 'PURE EV EPluto 7G', 'Hop Electric OXO',
       'PURE EV EcoDryft', 'Joy e-bike Wolf', 'Kinetic Green Zing',
       'Okinawa OKHI-90', 'Okinawa Praise', 'PURE EV Etryst 350',
       'Okinawa Dual 100', 'Okinawa Ridge Plus', 'Okinawa i-Praise',
       'Evolet Derby', 'Yo Drift', 'Yo Edge', 'Gemopai Ryder',
       'Gemopai Astrid Lite', 'Joy e-bike Glob', 'PURE EV ETrance Neo',
       'Odysse E2Go', 'Odysse Hawk', 'Odysse Racer', 'Bounce Infinity E1',
       'OPG Mobility Faast F4', 'OPG Mobility Freedum',
       'Hop Electric LEO', 'iVOOMi S1', 'iVOOMi Jeet X',
       'OPG Mobility Faast F2B', 'Okinawa Ridge 100', 'Joy e-bike Mihos',
       'Odysse Trot', 'OPG Mobility Faast F2F', 'Gemopai Ryder SuperMax',
       'Odysse Vader', 'Lectrix LXS 3.0', 'Kinetic Green Zulu',
       'Lectrix LXS 2.0', 'Quantum Energy Plasma',
       'Quantum Energy Bziness', 'Numeros Diplos', 'Numeros n-First'],
      dtype=object)

In [42]:
multi_word_brands = [
    "Royal Enfield",
    "Moto Morini",
    "Moto Guzzi",
    "QJ Motor",
    "Brixton Motorcycles",
    "Kinetic Green",
    "Quantum Energy",
    "Joy e-bike",
    "Bounce Infinity",
    "OPG Mobility",
    "Hop Electric",
    "PURE EV"
]

def get_brand(name):
    if pd.isna(name):
        return np.nan

    name = name.strip()

    for b in multi_word_brands:
        if name.startswith(b):
            return b

    return name.split()[0]

df1["Brand"] = df1["Model"].apply(get_brand)

In [43]:
df1.sample(2)

,Model,Rating,Rating_Members,Price,Top_Speed,Range,Weight,Battery,Brand
25,BGauss C12,4.5,51.0,109990,60.0,123,116.0,2.7,BGauss
11,OLA Roadster,4.6,176.0,104999,126.0,248,NaN,6.0,OLA

In [44]:
df1 = df1.rename(columns = {"Price": "Price(Rs)", "Top_Speed": "Top_Speed(kmph)","Range":"Range(km)" ,"Weight":"Weight(kg)" ,"Battery": "Battery(kwh)"})

In [45]:
df1 = df1[["Brand" ,"Model" ,"Rating"	,"Rating_Members" ,"Price(Rs)",	"Top_Speed(kmph)" , "Range(km)" ,"Weight(kg)" ,"Battery(kwh)"]]

In [46]:
df1[df1.duplicated(keep=False)].sort_values(by = "Model")

,Brand,Model,Rating,Rating_Members,Price(Rs),Top_Speed(kmph),Range(km),Weight(kg),Battery(kwh)
45,Ferrato,Ferrato FEV 650,3.3,2.0,159999,95.0,198,164.0,4.40
110,Ferrato,Ferrato FEV 650,3.3,2.0,159999,95.0,198,164.0,4.40
63,Raptee,Raptee HV T30,3.3,9.0,239000,135.0,200,177.0,5.40
112,Raptee,Raptee HV T30,3.3,9.0,239000,135.0,200,177.0,5.40
27,Royal Enfield,Royal Enfield Flying Flea C6,3.3,20.0,279000,115.0,154,124.0,3.91
113,Royal Enfield,Royal Enfield Flying Flea C6,3.3,20.0,279000,115.0,154,124.0,3.91
35,Ultraviolette,Ultraviolette F77 Mach 2,4.7,43.0,308994,155.0,323,207.0,10.30
109,Ultraviolette,Ultraviolette F77 Mach 2,4.7,43.0,308994,155.0,323,207.0,10.30
48,Ultraviolette,Ultraviolette F77 SuperStreet,4.4,8.0,308987,155.0,323,207.0,10.30
111,Ultraviolette,Ultraviolette F77 SuperStreet,4.4,8.0,308987,155.0,323,207.0,10.30

In [47]:
df1.drop_duplicates(inplace = True)

In [48]:
df1[df1.duplicated(keep=False)].sort_values(by = "Model")

Empty DataFrame
Columns: [Brand, Model, Rating, Rating_Members, Price(Rs), Top_Speed(kmph), Range(km), Weight(kg), Battery(kwh)]
Index: []

In [49]:
df1[df1[["Top_Speed(kmph)","Range(km)","Weight(kg)","Battery(kwh)"]].isna().sum(axis=1) >=1]

,Brand,Model,Rating,Rating_Members,Price(Rs),Top_Speed(kmph),Range(km),Weight(kg),Battery(kwh)
1,Bajaj,Bajaj Chetak,3.7,774.0,120236,80.0,153,NaN,3.50
5,VIDA,VIDA VX2,4.3,303.0,109936,90.0,187,NaN,4.40
11,OLA,OLA Roadster,4.6,176.0,104999,126.0,248,NaN,6.00
15,Simple,Simple Wave,NaN,8.0,109999,90.0,243,NaN,5.00
18,OLA,OLA Roadster Pro,4.8,131.0,199999,194.0,579,NaN,16.00
33,Honda,Honda QC3,2.5,1.0,135000,NaN,145,110.0,3.00
40,TVS,TVS X,3.7,26.0,264855,105.0,140,NaN,4.40
55,Okinawa,Okinawa R30,3.4,38.0,61998,25.0,60,NaN,1.34
66,Okinawa,Okinawa Lite,NaN,27.0,69087,25.0,60,NaN,1.25
73,Okinawa,Okinawa OKHI-90,3.8,60.0,149991,90.0,160,NaN,3.60
74,Okinawa,Okinawa Praise,2.6,392.0,85223,58.0,88,NaN,3.30
76,Okinawa,Okinawa Dual 100,2.5,6.0,119085,60.0,149,NaN,3.12
77,Okinawa,Okinawa Ridge Plus,3.1,44.0,90549,45.0,84,NaN,3.30
78,Okinawa,Okinawa i-Praise,3.5,58.0,123155,58.0,139,NaN,3.30
90,OPG Mobility,OPG Mobility Faast F4,3.8,23.0,111996,70.0,160,NaN,4.40
91,OPG Mobility,OPG Mobility Freedum,2.8,9.0,69999,25.0,75,NaN,1.40
95,OPG Mobility,OPG Mobility Faast F2B,3.3,7.0,91996,70.0,80,NaN,2.20
96,Okinawa,Okinawa Ridge 100,NaN,7.0,115311,50.0,149,NaN,3.12
99,OPG Mobility,OPG Mobility Faast F2F,NaN,NaN,81996,55.0,80,NaN,2.20

In [50]:
df1.isna().sum()

Brand               0
Model               0
Rating             17
Rating_Members      6
Price(Rs)           0
Top_Speed(kmph)     1
Range(km)           0
Weight(kg)         18
Battery(kwh)        0
dtype: int64

In [51]:
df1.isna().mean()*100

Brand               0.000000
Model               0.000000
Rating             15.740741
Rating_Members      5.555556
Price(Rs)           0.000000
Top_Speed(kmph)     0.925926
Range(km)           0.000000
Weight(kg)         16.666667
Battery(kwh)        0.000000
dtype: float64

In [52]:
df1.shape

(108, 9)

i think Weight(kg) is unwanted so iam dropping this column

In [53]:
df1.drop("Weight(kg)",axis=1,inplace = True)

In [54]:
df1.isna().mean()*100

Brand               0.000000
Model               0.000000
Rating             15.740741
Rating_Members      5.555556
Price(Rs)           0.000000
Top_Speed(kmph)     0.925926
Range(km)           0.000000
Battery(kwh)        0.000000
dtype: float64

In [55]:
df1.groupby(["Price(Rs)","Battery(kwh)"])["Top_Speed(kmph)"].mean().sort_values(ascending = False)

Price(Rs)  Battery(kwh)
199999     16.000          194.0
308994     10.300          155.0
308987     10.300          155.0
249000     10.300          145.0
135846     5.200           141.0
                           ...
71999      1.440            25.0
55799      1.152            25.0
99999      1.920            25.0
54999      1.340            25.0
135000     3.000             NaN
Name: Top_Speed(kmph), Length: 108, dtype: float64

In [56]:
df1[df1["Top_Speed(kmph)"].isna()][
    ["Brand", "Model", "Price(Rs)", "Range(km)", "Battery(kwh)"]
]

    Brand      Model  Price(Rs)  Range(km)  Battery(kwh)
33  Honda  Honda QC3     135000        145           3.0

In [57]:
similar_bikes = df1[
    (df1["Price(Rs)"].between(100000, 150000)) &
    (df1["Battery(kwh)"].between(2.5, 3.5)) &
    (df1["Top_Speed(kmph)"].notna())
]

similar_bikes[[
    "Brand", "Model", "Price(Rs)",
    "Battery(kwh)", "Top_Speed(kmph)"
]]

          Brand                Model  Price(Rs)  Battery(kwh)  Top_Speed(kmph)
1         Bajaj         Bajaj Chetak     120236          3.50             80.0
2         Ather         Ather Konarc     101209          3.50             70.0
3           TVS          TVS Orbiter     102434          3.10             68.0
4         Ather          Ather Rizta     121178          3.50             80.0
10        Bajaj     Bajaj Chetak C25     104600          2.50             55.0
12        Ather           Ather 450S     130283          3.50             90.0
14       Ampere  Ampere Magnus G Max     102999          3.00             65.0
17        Honda       Honda Activa e     120133          3.00             80.0
23       Ampere         Ampere Nexus     129999          3.00             93.0
25       BGauss           BGauss C12     109990          2.70             60.0
32         Oben        Oben Rorr EVO     139999          3.40            110.0
38      Kinetic           Kinetic DX     111499          3.10             90.0
39       Revolt         Revolt RV400     129951          3.24             85.0
50       Revolt           Revolt RVX     129990          3.24             90.0
54       Revolt     Revolt RV BlazeX     127988          3.24             85.0
57          VLF      VLF Tennis 1500     120225          2.50             65.0
59        Avore            Avore EX1     124999          3.24            100.0
67       BGauss    BGauss BG RUV 350     146990          3.00             75.0
70      PURE EV     PURE EV EcoDryft     118700          3.50             80.0
75      PURE EV   PURE EV Etryst 350     149999          3.50             94.0
76      Okinawa     Okinawa Dual 100     119085          3.12             60.0
78      Okinawa     Okinawa i-Praise     123155          3.30             58.0
83      Gemopai  Gemopai Astrid Lite     111195          2.88             65.0
96      Okinawa    Okinawa Ridge 100     115311          3.12             50.0
97   Joy e-bike     Joy e-bike Mihos     112997          2.88             65.0
108     Numeros      Numeros n-First     114999          3.00             70.0

In [58]:
similar_bikes["Top_Speed(kmph)"].median()

77.5

In [59]:
df1["Top_Speed(kmph)"] = df1["Top_Speed(kmph)"].fillna(
    similar_bikes["Top_Speed(kmph)"].median()
)

In [60]:
df1["Rating_Imputed"] = df1["Rating"].isna()

df1["Rating"] = df1["Rating"].fillna(
    df1.groupby("Brand")["Rating"].transform("median")
)

df1["Rating"] = df1["Rating"].fillna(df1["Rating"].median())

df1["Rating_Clean"] = df1["Rating"].where(~df1["Rating_Imputed"])

In [61]:
df1["Rating_Members"] = df1["Rating_Members"].fillna(0)

In [62]:
df1.isna().mean()*100

Brand               0.000000
Model               0.000000
Rating              0.000000
Rating_Members      0.000000
Price(Rs)           0.000000
Top_Speed(kmph)     0.000000
Range(km)           0.000000
Battery(kwh)        0.000000
Rating_Imputed      0.000000
Rating_Clean       15.740741
dtype: float64

# Export Cleaned DataSets

In [63]:
df.to_csv("Non_Electric_Cleaned_DataSet1.csv",index = False)

In [64]:
df1.to_csv("Electric_Cleaned_DataSet1.csv",index = False)